### ISSUE TITLE
Blog posts should have their own pages

### ISSUE THREAD

**Issue by jcn** [goruco/goruco2016#13]
For keeping the site manageable over time and to be able to link to things properly from the internet, we should be able to link to individual blog posts as individual pages. 

Was there a reason why this was not done? Technical limitations, etc?

**Comment by austenito** [comment]
@jcn @jordantomax pushed up a fix. See the homepage "Latest News Section", http://goruco.com/blog and http://goruco.com/2016/CFP-is-open

**Comment by jcn** [comment]
I like it!

**Comment by austenito** [comment]
Resolving with a verbal thumbs up from @jordantomax
