### ISSUE TITLE
Header Styles

### ISSUE THREAD

**Issue by jordantomax** [goruco/goruco2016#4]
General
- [ ] Header should be fixed and scroll with user
- [ ] Header background should be 85% opacity
- [ ] Header should have bottom border 3px solid #CF2941
- [ ] Header logo ruby is being stretched vertically

At desktop sizes:
- [ ] Header logo should be left aligned with grid
- [ ] Header navigation should be right aligned with grid

Typography:
- [ ] Reduce navigation letter spacing to 2px
- [ ] Navigation font-weight should be 500
- [ ] Logotype (GORUCO text) is not vertically centered

**Comment by jordantomax** [comment]
Looking better, a couple of things outstanding.

The header should be position: fixed, so it should follow you down the page. This will hopefully also fix that it should start sitting on top of the background X. The idea was to see some transparency on page load. Take a close look below:

<img width="1120" alt="screenshot 2016-03-20 16 06 27" src="https://cloud.githubusercontent.com/assets/37018/13906789/c1187124-eeb5-11e5-9d98-c9bc084d66f9.png">

**Comment by maggit** [comment]
@jordantomax take a look

**Comment by jordantomax** [comment]
Looks like we lost the position fixed as well as the bottom border.
