### ISSUE TITLE
Latest News Date is not correct type style

### ISSUE THREAD

**Issue by jordantomax** [goruco/goruco2016#9]
See attached screenshot from design. I'm referring to the date that sits right underneath "Latest News" That date should be 18px, centered, 70% opacity, and a bit closer to the header above. This style can be used for each section subheader.

<img width="979" alt="screenshot 2016-03-05 18 59 30" src="https://cloud.githubusercontent.com/assets/37018/13551333/6ebd3570-e304-11e5-8483-fec807e8ed0a.png">

**Comment by jordantomax** [comment]
Looks great under "Latest News", you can keep that just as it is. There are many blocks inside the "CFO is Open" content area of the same style that now look a little off. Inside that content area, can we left align those titles, and bring the opacity up to 1? See attached image. 
<img width="1035" alt="screenshot 2016-03-14 23 23 07" src="https://cloud.githubusercontent.com/assets/37018/13766867/0d3ad368-ea3c-11e5-9406-7ddde698fdad.png">

**Comment by austenito** [comment]
Gotcha. I'll fix those!
